# makefile.in generated by automake 1.14.1 from makefile.am.
# makefile.  Generated from makefile.in by configure.

# Copyright (C) 1994-2013 Free Software Foundation, Inc.

# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.



# mathomatic/makefile.am



am__is_gnu_make = test -n '$(MAKEFILE_LIST)' && test -n '$(MAKELEVEL)'
am__make_running_with_option = \
  case $${target_option-} in \
      ?) ;; \
      *) echo "am__make_running_with_option: internal error: invalid" \
              "target option '$${target_option-}' specified" >&2; \
         exit 1;; \
  esac; \
  has_opt=no; \
  sane_makeflags=$$MAKEFLAGS; \
  if $(am__is_gnu_make); then \
    sane_makeflags=$$MFLAGS; \
  else \
    case $$MAKEFLAGS in \
      *\\[\ \	]*) \
        bs=\\; \
        sane_makeflags=`printf '%s\n' "$$MAKEFLAGS" \
          | sed "s/$$bs$$bs[$$bs $$bs	]*//g"`;; \
    esac; \
  fi; \
  skip_next=no; \
  strip_trailopt () \
  { \
    flg=`printf '%s\n' "$$flg" | sed "s/$$1.*$$//"`; \
  }; \
  for flg in $$sane_makeflags; do \
    test $$skip_next = yes && { skip_next=no; continue; }; \
    case $$flg in \
      *=*|--*) continue;; \
        -*I) strip_trailopt 'I'; skip_next=yes;; \
      -*I?*) strip_trailopt 'I';; \
        -*O) strip_trailopt 'O'; skip_next=yes;; \
      -*O?*) strip_trailopt 'O';; \
        -*l) strip_trailopt 'l'; skip_next=yes;; \
      -*l?*) strip_trailopt 'l';; \
      -[dEDm]) skip_next=yes;; \
      -[JT]) skip_next=yes;; \
    esac; \
    case $$flg in \
      *$$target_option*) has_opt=yes; break;; \
    esac; \
  done; \
  test $$has_opt = yes
am__make_dryrun = (target_option=n; $(am__make_running_with_option))
am__make_keepgoing = (target_option=k; $(am__make_running_with_option))
pkgdatadir = $(datadir)/mathomatic
pkgincludedir = $(includedir)/mathomatic
pkglibdir = $(libdir)/mathomatic
pkglibexecdir = $(libexecdir)/mathomatic
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
bin_PROGRAMS = mathomatic$(EXEEXT)
subdir = .
DIST_COMMON = INSTALL NEWS README AUTHORS ChangeLog \
	$(srcdir)/makefile.in $(srcdir)/makefile.am \
	$(top_srcdir)/configure $(am__configure_deps) \
	$(srcdir)/config.h.in depcomp COPYING compile install-sh \
	missing
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
am__CONFIG_DISTCLEAN_FILES = config.status config.cache config.log \
 configure.lineno config.status.lineno
mkinstalldirs = $(install_sh) -d
CONFIG_HEADER = config.h
CONFIG_CLEAN_FILES =
CONFIG_CLEAN_VPATH_FILES =
LIBRARIES = $(noinst_LIBRARIES)
AR = ar
ARFLAGS = cru
AM_V_AR = $(am__v_AR_$(V))
am__v_AR_ = $(am__v_AR_$(AM_DEFAULT_VERBOSITY))
am__v_AR_0 = @echo "  AR      " $@;
am__v_AR_1 = 
libmathomatic_a_AR = $(AR) $(ARFLAGS)
libmathomatic_a_LIBADD =
am_libmathomatic_a_OBJECTS = globals.$(OBJEXT) am.$(OBJEXT) \
	solve.$(OBJEXT) help.$(OBJEXT) parse.$(OBJEXT) cmds.$(OBJEXT) \
	simplify.$(OBJEXT) factor.$(OBJEXT) super.$(OBJEXT) \
	unfactor.$(OBJEXT) poly.$(OBJEXT) diff.$(OBJEXT) \
	integrate.$(OBJEXT) complex.$(OBJEXT) complex_lib.$(OBJEXT) \
	list.$(OBJEXT) gcd.$(OBJEXT) factor_int.$(OBJEXT)
libmathomatic_a_OBJECTS = $(am_libmathomatic_a_OBJECTS)
am__installdirs = "$(DESTDIR)$(bindir)"
PROGRAMS = $(bin_PROGRAMS)
am_mathomatic_OBJECTS = main.$(OBJEXT)
mathomatic_OBJECTS = $(am_mathomatic_OBJECTS)
mathomatic_DEPENDENCIES = libmathomatic.a
AM_V_P = $(am__v_P_$(V))
am__v_P_ = $(am__v_P_$(AM_DEFAULT_VERBOSITY))
am__v_P_0 = false
am__v_P_1 = :
AM_V_GEN = $(am__v_GEN_$(V))
am__v_GEN_ = $(am__v_GEN_$(AM_DEFAULT_VERBOSITY))
am__v_GEN_0 = @echo "  GEN     " $@;
am__v_GEN_1 = 
AM_V_at = $(am__v_at_$(V))
am__v_at_ = $(am__v_at_$(AM_DEFAULT_VERBOSITY))
am__v_at_0 = @
am__v_at_1 = 
DEFAULT_INCLUDES = -I.
depcomp = $(SHELL) $(top_srcdir)/depcomp
am__depfiles_maybe = depfiles
am__mv = mv -f
COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
AM_V_CC = $(am__v_CC_$(V))
am__v_CC_ = $(am__v_CC_$(AM_DEFAULT_VERBOSITY))
am__v_CC_0 = @echo "  CC      " $@;
am__v_CC_1 = 
CCLD = $(CC)
LINK = $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(AM_LDFLAGS) $(LDFLAGS) -o $@
AM_V_CCLD = $(am__v_CCLD_$(V))
am__v_CCLD_ = $(am__v_CCLD_$(AM_DEFAULT_VERBOSITY))
am__v_CCLD_0 = @echo "  CCLD    " $@;
am__v_CCLD_1 = 
SOURCES = $(libmathomatic_a_SOURCES) $(mathomatic_SOURCES)
DIST_SOURCES = $(libmathomatic_a_SOURCES) $(mathomatic_SOURCES)
am__can_run_installinfo = \
  case $$AM_UPDATE_INFO_DIR in \
    n|no|NO) false;; \
    *) (install-info --version) >/dev/null 2>&1;; \
  esac
am__tagged_files = $(HEADERS) $(SOURCES) $(TAGS_FILES) \
	$(LISP)config.h.in
# Read a list of newline-separated strings from the standard input,
# and print each of them once, without duplicates.  Input order is
# *not* preserved.
am__uniquify_input = $(AWK) '\
  BEGIN { nonempty = 0; } \
  { items[$$0] = 1; nonempty = 1; } \
  END { if (nonempty) { for (i in items) print i; }; } \
'
# Make sure the list of sources is unique.  This is necessary because,
# e.g., the same source file might be shared among _SOURCES variables
# for different programs/libraries.
am__define_uniq_tagged_files = \
  list='$(am__tagged_files)'; \
  unique=`for i in $$list; do \
    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
  done | $(am__uniquify_input)`
ETAGS = etags
CTAGS = ctags
CSCOPE = cscope
AM_RECURSIVE_TARGETS = cscope
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
distdir = $(PACKAGE)-$(VERSION)
top_distdir = $(distdir)
am__remove_distdir = \
  if test -d "$(distdir)"; then \
    find "$(distdir)" -type d ! -perm -200 -exec chmod u+w {} ';' \
      && rm -rf "$(distdir)" \
      || { sleep 5 && rm -rf "$(distdir)"; }; \
  else :; fi
am__post_remove_distdir = $(am__remove_distdir)
DIST_ARCHIVES = $(distdir).tar.gz
GZIP_ENV = --best
DIST_TARGETS = dist-gzip
distuninstallcheck_listfiles = find . -type f -print
am__distuninstallcheck_listfiles = $(distuninstallcheck_listfiles) \
  | sed 's|^\./|$(prefix)/|' | grep -v '$(infodir)/dir$$'
distcleancheck_listfiles = find . -type f -print
ACLOCAL = ${SHELL} /home/rubicks/code/mathomatic/missing aclocal-1.14
AMTAR = $${TAR-tar}
AM_DEFAULT_VERBOSITY = 1
AUTOCONF = ${SHELL} /home/rubicks/code/mathomatic/missing autoconf
AUTOHEADER = ${SHELL} /home/rubicks/code/mathomatic/missing autoheader
AUTOMAKE = ${SHELL} /home/rubicks/code/mathomatic/missing automake-1.14
AWK = gawk
CC = gcc
CCDEPMODE = depmode=gcc3
CFLAGS = -g -O2
CPP = gcc -E
CPPFLAGS = 
CXX = g++
CXXDEPMODE = depmode=gcc3
CXXFLAGS = -g -O2
CYGPATH_W = echo
DEFS = -DHAVE_CONFIG_H
DEPDIR = .deps
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EGREP = /usr/bin/grep -E
EXEEXT = 
GREP = /usr/bin/grep
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
LDFLAGS = 
LIBOBJS = 
LIBS = -lm 
LN_S = ln -s
LTLIBOBJS = 
MAKEINFO = ${SHELL} /home/rubicks/code/mathomatic/missing makeinfo
MKDIR_P = /usr/bin/mkdir -p
OBJEXT = o
PACKAGE = mathomatic
PACKAGE_BUGREPORT = rubicks00@gmail.com
PACKAGE_NAME = mathomatic
PACKAGE_STRING = mathomatic 16.0.5
PACKAGE_TARNAME = mathomatic
PACKAGE_URL = 
PACKAGE_VERSION = 16.0.5
PATH_SEPARATOR = :
POW_LIB = 
RANLIB = ranlib
SET_MAKE = 
SHELL = /bin/sh
STRIP = 
VERSION = 16.0.5
abs_builddir = /home/rubicks/code/mathomatic
abs_srcdir = /home/rubicks/code/mathomatic
abs_top_builddir = /home/rubicks/code/mathomatic
abs_top_srcdir = /home/rubicks/code/mathomatic
ac_ct_CC = gcc
ac_ct_CXX = g++
am__include = include
am__leading_dot = .
am__quote = 
am__tar = $${TAR-tar} chof - "$$tardir"
am__untar = $${TAR-tar} xf -
bindir = ${exec_prefix}/bin
build_alias = 
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
exec_prefix = ${prefix}
host_alias = 
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = ${SHELL} /home/rubicks/code/mathomatic/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
mandir = ${datarootdir}/man
mkdir_p = $(MKDIR_P)
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /home/rubicks
program_transform_name = s,x,x,
psdir = ${docdir}
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
sysconfdir = ${prefix}/etc
target_alias = 
top_build_prefix = 
top_builddir = .
top_srcdir = .
noinst_LIBRARIES = libmathomatic.a
libmathomatic_a_SOURCES = globals.c am.c solve.c help.c parse.c cmds.c		\
simplify.c factor.c super.c unfactor.c poly.c diff.c integrate.c complex.c	\
complex_lib.c list.c gcd.c factor_int.c

mathomatic_SOURCES = main.c
mathomatic_LDADD = libmathomatic.a
all: config.h
	$(MAKE) $(AM_MAKEFLAGS) all-am

.SUFFIXES:
.SUFFIXES: .c .o .obj
am--refresh: makefile
	@:
$(srcdir)/makefile.in:  $(srcdir)/makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      echo ' cd $(srcdir) && $(AUTOMAKE) --gnu'; \
	      $(am__cd) $(srcdir) && $(AUTOMAKE) --gnu \
		&& exit 0; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --gnu makefile'; \
	$(am__cd) $(top_srcdir) && \
	  $(AUTOMAKE) --gnu makefile
.PRECIOUS: makefile
makefile: $(srcdir)/makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    echo ' $(SHELL) ./config.status'; \
	    $(SHELL) ./config.status;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	$(SHELL) ./config.status --recheck

$(top_srcdir)/configure:  $(am__configure_deps)
	$(am__cd) $(srcdir) && $(AUTOCONF)
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	$(am__cd) $(srcdir) && $(ACLOCAL) $(ACLOCAL_AMFLAGS)
$(am__aclocal_m4_deps):

config.h: stamp-h1
	@test -f $@ || rm -f stamp-h1
	@test -f $@ || $(MAKE) $(AM_MAKEFLAGS) stamp-h1

stamp-h1: $(srcdir)/config.h.in $(top_builddir)/config.status
	@rm -f stamp-h1
	cd $(top_builddir) && $(SHELL) ./config.status config.h
$(srcdir)/config.h.in:  $(am__configure_deps) 
	($(am__cd) $(top_srcdir) && $(AUTOHEADER))
	rm -f stamp-h1
	touch $@

distclean-hdr:
	-rm -f config.h stamp-h1

clean-noinstLIBRARIES:
	-test -z "$(noinst_LIBRARIES)" || rm -f $(noinst_LIBRARIES)

libmathomatic.a: $(libmathomatic_a_OBJECTS) $(libmathomatic_a_DEPENDENCIES) $(EXTRA_libmathomatic_a_DEPENDENCIES) 
	$(AM_V_at)-rm -f libmathomatic.a
	$(AM_V_AR)$(libmathomatic_a_AR) libmathomatic.a $(libmathomatic_a_OBJECTS) $(libmathomatic_a_LIBADD)
	$(AM_V_at)$(RANLIB) libmathomatic.a
install-binPROGRAMS: $(bin_PROGRAMS)
	@$(NORMAL_INSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(bindir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(bindir)" || exit 1; \
	fi; \
	for p in $$list; do echo "$$p $$p"; done | \
	sed 's/$(EXEEXT)$$//' | \
	while read p p1; do if test -f $$p \
	  ; then echo "$$p"; echo "$$p"; else :; fi; \
	done | \
	sed -e 'p;s,.*/,,;n;h' \
	    -e 's|.*|.|' \
	    -e 'p;x;s,.*/,,;s/$(EXEEXT)$$//;$(transform);s/$$/$(EXEEXT)/' | \
	sed 'N;N;N;s,\n, ,g' | \
	$(AWK) 'BEGIN { files["."] = ""; dirs["."] = 1 } \
	  { d=$$3; if (dirs[d] != 1) { print "d", d; dirs[d] = 1 } \
	    if ($$2 == $$4) files[d] = files[d] " " $$1; \
	    else { print "f", $$3 "/" $$4, $$1; } } \
	  END { for (d in files) print "f", d, files[d] }' | \
	while read type dir files; do \
	    if test "$$dir" = .; then dir=; else dir=/$$dir; fi; \
	    test -z "$$files" || { \
	      echo " $(INSTALL_PROGRAM_ENV) $(INSTALL_PROGRAM) $$files '$(DESTDIR)$(bindir)$$dir'"; \
	      $(INSTALL_PROGRAM_ENV) $(INSTALL_PROGRAM) $$files "$(DESTDIR)$(bindir)$$dir" || exit $$?; \
	    } \
	; done

uninstall-binPROGRAMS:
	@$(NORMAL_UNINSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	files=`for p in $$list; do echo "$$p"; done | \
	  sed -e 'h;s,^.*/,,;s/$(EXEEXT)$$//;$(transform)' \
	      -e 's/$$/$(EXEEXT)/' \
	`; \
	test -n "$$list" || exit 0; \
	echo " ( cd '$(DESTDIR)$(bindir)' && rm -f" $$files ")"; \
	cd "$(DESTDIR)$(bindir)" && rm -f $$files

clean-binPROGRAMS:
	-test -z "$(bin_PROGRAMS)" || rm -f $(bin_PROGRAMS)

mathomatic$(EXEEXT): $(mathomatic_OBJECTS) $(mathomatic_DEPENDENCIES) $(EXTRA_mathomatic_DEPENDENCIES) 
	@rm -f mathomatic$(EXEEXT)
	$(AM_V_CCLD)$(LINK) $(mathomatic_OBJECTS) $(mathomatic_LDADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT)

distclean-compile:
	-rm -f *.tab.c

include ./$(DEPDIR)/am.Po
include ./$(DEPDIR)/cmds.Po
include ./$(DEPDIR)/complex.Po
include ./$(DEPDIR)/complex_lib.Po
include ./$(DEPDIR)/diff.Po
include ./$(DEPDIR)/factor.Po
include ./$(DEPDIR)/factor_int.Po
include ./$(DEPDIR)/gcd.Po
include ./$(DEPDIR)/globals.Po
include ./$(DEPDIR)/help.Po
include ./$(DEPDIR)/integrate.Po
include ./$(DEPDIR)/list.Po
include ./$(DEPDIR)/main.Po
include ./$(DEPDIR)/parse.Po
include ./$(DEPDIR)/poly.Po
include ./$(DEPDIR)/simplify.Po
include ./$(DEPDIR)/solve.Po
include ./$(DEPDIR)/super.Po
include ./$(DEPDIR)/unfactor.Po

.c.o:
	$(AM_V_CC)$(COMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ $<
	$(AM_V_at)$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	$(AM_V_CC)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(COMPILE) -c -o $@ $<

.c.obj:
	$(AM_V_CC)$(COMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ `$(CYGPATH_W) '$<'`
	$(AM_V_at)$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	$(AM_V_CC)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(COMPILE) -c -o $@ `$(CYGPATH_W) '$<'`

ID: $(am__tagged_files)
	$(am__define_uniq_tagged_files); mkid -fID $$unique
tags: tags-am
TAGS: tags

tags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	set x; \
	here=`pwd`; \
	$(am__define_uniq_tagged_files); \
	shift; \
	if test -z "$(ETAGS_ARGS)$$*$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  if test $$# -gt 0; then \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      "$$@" $$unique; \
	  else \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      $$unique; \
	  fi; \
	fi
ctags: ctags-am

CTAGS: ctags
ctags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	$(am__define_uniq_tagged_files); \
	test -z "$(CTAGS_ARGS)$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && $(am__cd) $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) "$$here"
cscope: cscope.files
	test ! -s cscope.files \
	  || $(CSCOPE) -b -q $(AM_CSCOPEFLAGS) $(CSCOPEFLAGS) -i cscope.files $(CSCOPE_ARGS)
clean-cscope:
	-rm -f cscope.files
cscope.files: clean-cscope cscopelist
cscopelist: cscopelist-am

cscopelist-am: $(am__tagged_files)
	list='$(am__tagged_files)'; \
	case "$(srcdir)" in \
	  [\\/]* | ?:[\\/]*) sdir="$(srcdir)" ;; \
	  *) sdir=$(subdir)/$(srcdir) ;; \
	esac; \
	for i in $$list; do \
	  if test -f "$$i"; then \
	    echo "$(subdir)/$$i"; \
	  else \
	    echo "$$sdir/$$i"; \
	  fi; \
	done >> $(top_builddir)/cscope.files

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags
	-rm -f cscope.out cscope.in.out cscope.po.out cscope.files

distdir: $(DISTFILES)
	$(am__remove_distdir)
	test -d "$(distdir)" || mkdir "$(distdir)"
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d "$(distdir)/$$file"; then \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -fpR $(srcdir)/$$file "$(distdir)$$dir" || exit 1; \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    cp -fpR $$d/$$file "$(distdir)$$dir" || exit 1; \
	  else \
	    test -f "$(distdir)/$$file" \
	    || cp -p $$d/$$file "$(distdir)/$$file" \
	    || exit 1; \
	  fi; \
	done
	-test -n "$(am__skip_mode_fix)" \
	|| find "$(distdir)" -type d ! -perm -755 \
		-exec chmod u+rwx,go+rx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec $(install_sh) -c -m a+r {} {} \; \
	|| chmod -R a+r "$(distdir)"
dist-gzip: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__post_remove_distdir)

dist-bzip2: distdir
	tardir=$(distdir) && $(am__tar) | BZIP2=$${BZIP2--9} bzip2 -c >$(distdir).tar.bz2
	$(am__post_remove_distdir)

dist-lzip: distdir
	tardir=$(distdir) && $(am__tar) | lzip -c $${LZIP_OPT--9} >$(distdir).tar.lz
	$(am__post_remove_distdir)

dist-xz: distdir
	tardir=$(distdir) && $(am__tar) | XZ_OPT=$${XZ_OPT--e} xz -c >$(distdir).tar.xz
	$(am__post_remove_distdir)

dist-tarZ: distdir
	@echo WARNING: "Support for shar distribution archives is" \
	               "deprecated." >&2
	@echo WARNING: "It will be removed altogether in Automake 2.0" >&2
	tardir=$(distdir) && $(am__tar) | compress -c >$(distdir).tar.Z
	$(am__post_remove_distdir)

dist-shar: distdir
	@echo WARNING: "Support for distribution archives compressed with" \
		       "legacy program 'compress' is deprecated." >&2
	@echo WARNING: "It will be removed altogether in Automake 2.0" >&2
	shar $(distdir) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).shar.gz
	$(am__post_remove_distdir)

dist-zip: distdir
	-rm -f $(distdir).zip
	zip -rq $(distdir).zip $(distdir)
	$(am__post_remove_distdir)

dist dist-all:
	$(MAKE) $(AM_MAKEFLAGS) $(DIST_TARGETS) am__post_remove_distdir='@:'
	$(am__post_remove_distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	case '$(DIST_ARCHIVES)' in \
	*.tar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).tar.gz | $(am__untar) ;;\
	*.tar.bz2*) \
	  bzip2 -dc $(distdir).tar.bz2 | $(am__untar) ;;\
	*.tar.lz*) \
	  lzip -dc $(distdir).tar.lz | $(am__untar) ;;\
	*.tar.xz*) \
	  xz -dc $(distdir).tar.xz | $(am__untar) ;;\
	*.tar.Z*) \
	  uncompress -c $(distdir).tar.Z | $(am__untar) ;;\
	*.shar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).shar.gz | unshar ;;\
	*.zip*) \
	  unzip $(distdir).zip ;;\
	esac
	chmod -R a-w $(distdir)
	chmod u+w $(distdir)
	mkdir $(distdir)/_build $(distdir)/_inst
	chmod a-w $(distdir)
	test -d $(distdir)/_build || exit 0; \
	dc_install_base=`$(am__cd) $(distdir)/_inst && pwd | sed -e 's,^[^:\\/]:[\\/],/,'` \
	  && dc_destdir="$${TMPDIR-/tmp}/am-dc-$$$$/" \
	  && am__cwd=`pwd` \
	  && $(am__cd) $(distdir)/_build \
	  && ../configure \
	    $(AM_DISTCHECK_CONFIGURE_FLAGS) \
	    $(DISTCHECK_CONFIGURE_FLAGS) \
	    --srcdir=.. --prefix="$$dc_install_base" \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) dvi \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
	  && $(MAKE) $(AM_MAKEFLAGS) installcheck \
	  && $(MAKE) $(AM_MAKEFLAGS) uninstall \
	  && $(MAKE) $(AM_MAKEFLAGS) distuninstallcheck_dir="$$dc_install_base" \
	        distuninstallcheck \
	  && chmod -R a-w "$$dc_install_base" \
	  && ({ \
	       (cd ../.. && umask 077 && mkdir "$$dc_destdir") \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" install \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" uninstall \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" \
	            distuninstallcheck_dir="$$dc_destdir" distuninstallcheck; \
	      } || { rm -rf "$$dc_destdir"; exit 1; }) \
	  && rm -rf "$$dc_destdir" \
	  && $(MAKE) $(AM_MAKEFLAGS) dist \
	  && rm -rf $(DIST_ARCHIVES) \
	  && $(MAKE) $(AM_MAKEFLAGS) distcleancheck \
	  && cd "$$am__cwd" \
	  || exit 1
	$(am__post_remove_distdir)
	@(echo "$(distdir) archives ready for distribution: "; \
	  list='$(DIST_ARCHIVES)'; for i in $$list; do echo $$i; done) | \
	  sed -e 1h -e 1s/./=/g -e 1p -e 1x -e '$$p' -e '$$x'
distuninstallcheck:
	@test -n '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: trying to run $@ with an empty' \
	       '$$(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	$(am__cd) '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: cannot chdir into $(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	test `$(am__distuninstallcheck_listfiles) | wc -l` -eq 0 \
	   || { echo "ERROR: files left after uninstall:" ; \
	        if test -n "$(DESTDIR)"; then \
	          echo "  (check DESTDIR support)"; \
	        fi ; \
	        $(distuninstallcheck_listfiles) ; \
	        exit 1; } >&2
distcleancheck: distclean
	@if test '$(srcdir)' = . ; then \
	  echo "ERROR: distcleancheck can only run from a VPATH build" ; \
	  exit 1 ; \
	fi
	@test `$(distcleancheck_listfiles) | wc -l` -eq 0 \
	  || { echo "ERROR: files left in build directory after distclean:" ; \
	       $(distcleancheck_listfiles) ; \
	       exit 1; } >&2
check-am: all-am
check: check-am
all-am: makefile $(LIBRARIES) $(PROGRAMS) config.h
installdirs:
	for dir in "$(DESTDIR)$(bindir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	if test -z '$(STRIP)'; then \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	      install; \
	else \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	    "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'" install; \
	fi
mostlyclean-generic:

clean-generic:

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
	-test . = "$(srcdir)" || test -z "$(CONFIG_CLEAN_VPATH_FILES)" || rm -f $(CONFIG_CLEAN_VPATH_FILES)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-am

clean-am: clean-binPROGRAMS clean-generic clean-noinstLIBRARIES \
	mostlyclean-am

distclean: distclean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf ./$(DEPDIR)
	-rm -f makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-hdr distclean-tags

dvi: dvi-am

dvi-am:

html: html-am

html-am:

info: info-am

info-am:

install-data-am:

install-dvi: install-dvi-am

install-dvi-am:

install-exec-am: install-binPROGRAMS

install-html: install-html-am

install-html-am:

install-info: install-info-am

install-info-am:

install-man:

install-pdf: install-pdf-am

install-pdf-am:

install-ps: install-ps-am

install-ps-am:

installcheck-am:

maintainer-clean: maintainer-clean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf $(top_srcdir)/autom4te.cache
	-rm -rf ./$(DEPDIR)
	-rm -f makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic

pdf: pdf-am

pdf-am:

ps: ps-am

ps-am:

uninstall-am: uninstall-binPROGRAMS

.MAKE: all install-am install-strip

.PHONY: CTAGS GTAGS TAGS all all-am am--refresh check check-am clean \
	clean-binPROGRAMS clean-cscope clean-generic \
	clean-noinstLIBRARIES cscope cscopelist-am ctags ctags-am dist \
	dist-all dist-bzip2 dist-gzip dist-lzip dist-shar dist-tarZ \
	dist-xz dist-zip distcheck distclean distclean-compile \
	distclean-generic distclean-hdr distclean-tags distcleancheck \
	distdir distuninstallcheck dvi dvi-am html html-am info \
	info-am install install-am install-binPROGRAMS install-data \
	install-data-am install-dvi install-dvi-am install-exec \
	install-exec-am install-html install-html-am install-info \
	install-info-am install-man install-pdf install-pdf-am \
	install-ps install-ps-am install-strip installcheck \
	installcheck-am installdirs maintainer-clean \
	maintainer-clean-generic mostlyclean mostlyclean-compile \
	mostlyclean-generic pdf pdf-am ps ps-am tags tags-am uninstall \
	uninstall-am uninstall-binPROGRAMS


# # appended makefile follows

# # Makefile for compiling, testing, and installing Mathomatic and its documentation.
# # Requires the GNU make utility, in BSD Unix this is called "gmake".
# # Remove the -DUNIX define in CFLAGS when not using Mathomatic for desktop UNIX/Linux.

# # For normal compilation and testing on a GNU system,
# # please type the following at the shell prompt:
# #	make clean
# # 	make READLINE=1
# # 	make test
# #
# # For Slackware, or any other OS that fails to find the curses library functions, use:
# #	LDLIBS=-lncurses make READLINE=1
# # for the second make line.
# #
# # To use the Tiny C Compiler (tcc) to compile Mathomatic:
# #	make clean
# #	CC=tcc LDFLAGS="-L/usr/lib/x86_64-linux-gnu/ -L/lib/x86_64-linux-gnu/" make READLINE=1
# #	make test
# # The -L options might need to be set to the library directories your current gcc uses,
# # as the above example shows.
# # They will probably differ from the above, try "locate libm." to find your library paths,
# # one or two of them will probably work.

# # To install the base Mathomatic system after compiling and testing, type:
# #	make install
# # if that doesn't work, try:
# #	sudo make install
# # and enter your password.  This is because write permission is required to /usr/local/*.
# #
# # To install all of Mathomatic, including m4 Mathomatic (rmath), instead type:
# #	make m4install
# # or:
# #	sudo make m4install

# # To compile, test, and install all of Mathomatic under CygWin for MS-Windows:
# # 	CFLAGS="-DCYGWIN -DBOLD_COLOR -O3" make READLINE=1
# #	make test
# #	make m4install

# # To compile Mathomatic with the MinGW cross-compiler for MS-Windows under Debian or Ubuntu:
# #	sudo apt-get install gcc-mingw32
# #	./compile.mingw
# # This will create Windows executables for Mathomatic and the Prime Number Tools.
# # For cross-compiling under other systems, just edit "compile.mingw".

# # To compile, test, and install all of Mathomatic under OpenIndiana (SunOS), type:
# #	LDLIBS=-lcurses make READLINE=1
# #	make test
# #	sudo make m4install INSTALL=ginstall prefix=/usr M4=gm4

# # This makefile does NOT compile and install the Prime Number Tools in the "primes" directory,
# # nor does it compile and install the Symbolic Math Library in the "lib" directory.
# #	sudo make uninstall
# # here will uninstall all of Mathomatic,
# # including the Prime Number Tools and the Symbolic Math Library,
# # but it must know the "prefix" used to install Mathomatic, if specified during the install.

# SHELL		= /bin/sh # from "http://www.gnu.org/prep/standards/", do not change
# CC		?= gcc # C compiler to use; this statement doesn't work usually, instead using cc.
# M4		?= m4 # Change this to gm4 in Unix or a non-GNU system.
# INSTALL		?= install # Installer utility to use; change to ginstall under Unix.
# INSTALL_PROGRAM	?= $(INSTALL) # Command to install executable program files.
# INSTALL_DATA	?= $(INSTALL) -m 0644 # Command to install data files.

# CC_OPTIMIZE	?= -O3 # Default C compiler optimization flags that are safe (but please remove for LLVM/Clang, see "misc/known_bugs.txt").
# # Be sure and run tests to see if Mathomatic works and runs faster, if you uncomment the following line:
# #CC_OPTIMIZE	+= -fno-signaling-nans -fno-trapping-math -fomit-frame-pointer # Possible additional optimizations, not tested.

# VERSION		= `cat VERSION`
# OPTFLAGS	?= $(CC_OPTIMIZE) -Wall -Wshadow -Wno-char-subscripts # optional gcc specific flags
# CFLAGS		?= $(OPTFLAGS)
# CFLAGS		+= -fexceptions -DUNIX -DVERSION=\"$(VERSION)\"
# LDLIBS		+= -lm # libraries to link with to create the Mathomatic executable

# # Run "make READLINE=1" to include the optional readline editing and history support:
# CFLAGS		+= $(READLINE:1=-DREADLINE)
# LDLIBS		+= $(READLINE:1=-lreadline) # Add -lncurses if needed for readline, might be called "curses" on some systems.
# # Run "make EDITLINE=1" to include the optional editline editing and history support (smaller than readline):
# CFLAGS		+= $(EDITLINE:1=-DEDITLINE)
# LDLIBS		+= $(EDITLINE:1=-leditline)

# # Uncomment the following line to force generation of x86-64-bit code:
# #CFLAGS		+= -m64

# # Install directories follow; installs everything in $(DESTDIR)/usr/local by default.
# # Note that support for the DESTDIR variable was added in version 15.2.1.
# # DESTDIR is used by package maintainers, who should remove all DESTDIR patches,
# # because DESTDIR is handled properly (according to GNU standards) by this makefile now.
# prefix		?= /usr/local
# bindir		?= $(prefix)/bin
# datadir		?= $(prefix)/share
# mandir		?= $(prefix)/share/man
# docdir		?= $(prefix)/share/doc
# mathdocdir	?= $(docdir)/mathomatic
# mathdatadir	?= $(datadir)/mathomatic

# # Mathomatic program names:
# AOUT		?= mathomatic
# M4SCRIPTPATH	= $(DESTDIR)$(bindir)/matho

# INCLUDES	= includes.h license.h standard.h am.h externs.h blt.h complex.h proto.h altproto.h
# MATHOMATIC_OBJECTS += main.o globals.o am.o solve.o help.o parse.o cmds.o simplify.o \
# 		  factor.o super.o unfactor.o poly.o diff.o integrate.o \
# 		  complex.o complex_lib.o list.o gcd.o factor_int.o

# PRIMES_MANHTML	= doc/matho-primes.1.html doc/matho-pascal.1.html doc/matho-sumsq.1.html \
# 		  doc/primorial.1.html doc/matho-mult.1.html doc/matho-sum.1.html
# # HTML man pages to make:
# MANHTML		= doc/mathomatic.1.html doc/rmath.1.html $(PRIMES_MANHTML)

# # Flags to make HTML man pages with rman:
# RMANOPTS	= -f HTML -r '%s.%s.html'
# RMAN		= rman
# # Flags to make HTML man pages with groff instead (uncomment below and comment above to use):
# #RMANOPTS       = -man -Thtml -P -l 
# #RMAN		= groff

# # man pages to install:
# MAN1		= mathomatic.1 rmath.1
# # Text files to install:
# TEXT_DOCS	?= VERSION AUTHORS COPYING README.txt NEWS

# PDFDOC		= manual.pdf	# Name of PDF file containing the Mathomatic User Guide and Command Reference.
# PDFMAN		= bookman.pdf	# Name of PDF file containing all the Mathomatic man pages.

# all static: $(AOUT) html NEWS # make these by default

# # Make sure the HTML man pages are up-to-date.
# html: $(MANHTML)

# # Make the Quick Reference Card.
# htmlcard doc/quickrefcard.html: $(AOUT)
# 	./makehtmlcard.sh doc/ # shell script that uses awk to make a nice command reference card

# # Make the PDF cheat sheet.
# pdfsheet quickref.pdf: $(AOUT)
# 	./makepdfsheet.sh doc/ # shell script

# # TEST MATHOMATIC

# # Run "make test" to see if the resulting mathomatic executable runs properly on your system.
# # It does a diff between the output of the test and the expected output.
# # If no differences are reported, "All tests passed 100% correctly" is displayed.
# test:
# 	@echo
# 	@echo Testing ./$(AOUT)	\(`./$(AOUT) -v`\)
# 	cd tests && time -p ../$(AOUT) -t all 0<&- >test.out && diff -u --strip-trailing-cr all.out test.out && rm test.out && cd ..
# 	@echo "All tests passed 100% correctly."

# # Same as "make test", except it doesn't run the time command.
# check:
# 	@echo
# 	@echo Testing ./$(AOUT)	\(`./$(AOUT) -v`\)
# 	cd tests && ../$(AOUT) -t all 0<&- >test.out && diff -u --strip-trailing-cr all.out test.out && rm test.out && cd ..
# 	@echo "All tests passed 100% correctly."

# # "make baseline" generates the expected output file for "make test".
# # Do not run this unless you are sure Mathomatic is working correctly
# # and you need "make test" to succeed with no errors.
# baseline tests/all.out:
# 	cd tests && ../$(AOUT) -t all 0<&- >all.out && cd ..
# 	@rm -f tests/test.out
# 	@echo
# 	@echo File tests/all.out updated with current test output.

# # BUILD MATHOMATIC

# # ./update updates the function prototypes in proto.h by using the cproto utility.
# # Run ./update whenever a new C function is added to the Mathomatic source code or
# # whenever a function definition is changed.
# proto.h:
# 	./update # shell script

# $(MATHOMATIC_OBJECTS): $(INCLUDES) VERSION

# # To compile Mathomatic as a stand-alone executable
# # that has no shared library dependencies, type "make clean static".
# static: LDFLAGS += -static

# # Create the mathomatic executable:
# $(AOUT): $(MATHOMATIC_OBJECTS)
# 	$(CC) $(CFLAGS) $(LDFLAGS) $+ $(LDLIBS) -o $(AOUT)
# 	@echo
# 	@echo ./$(AOUT) successfully created.

# # BUILD THE MATHOMATIC DOCUMENTATION

# # Build the nicely ordered changelog.
# NEWS: changes.txt makenews.sh
# 	./makenews.sh # shell script

# # "make pdfdoc" creates the PDF version of the Mathomatic User Guide and Command Reference, if desired.
# # Requires the htmldoc program be installed.
# pdf pdfdoc $(PDFDOC): doc/manual.html doc/am.html doc/fdl-1.3-standalone.html
# 	htmldoc --webpage --format pdf --title --logoimage icons/mathomatic.png --footer h1l --header "c d" -f $(PDFDOC) $+
# 	@echo Mathomatic PDF user documentation $(PDFDOC) generated.

# # "make pdfman" creates a PDF of all the Mathomatic Man pages, if desired.
# # Requires the very latest version of the txt2man package.
# bookman pdfman $(PDFMAN): $(MAN1) primes/*.1 lib/*.3
# 	bookman -p -t "Mathomatic version $(VERSION) Man Pages" -a "George Gesslein II" -d `date +%F` $+ >$(PDFMAN) </dev/null
# 	@echo Complete Mathomatic PDF man pages book created in $(PDFMAN)

# # Here we convert the man pages to HTML docs with rman:
# doc/mathomatic.1.html: mathomatic.1
# 	$(RMAN) $(RMANOPTS) $< >/dev/null # Test for the success of rman command.
# 	@tidy -version >/dev/null
# 	-$(RMAN) $(RMANOPTS) $< | tidy -q -i -file /dev/null >$@
# 	@echo Successfully created $@

# doc/rmath.1.html: rmath.1
# 	$(RMAN) $(RMANOPTS) $< >/dev/null # Test for the success of rman command.
# 	@tidy -version >/dev/null
# 	-$(RMAN) $(RMANOPTS) $< | tidy -q -i -file /dev/null >$@
# 	@echo Successfully created $@

# $(PRIMES_MANHTML): doc/%.1.html: primes/%.1
# 	$(RMAN) $(RMANOPTS) $< >/dev/null # Test for the success of rman command.
# 	@tidy -version >/dev/null
# 	-$(RMAN) $(RMANOPTS) $< | tidy -q -i -file /dev/null >$@
# 	@echo Successfully created $@

# # INSTALL MATHOMATIC

# # The following installs everything, including m4 Mathomatic with documentation.
# m4install: install matho-rmath-install
# 	@echo
# 	@echo m4 Mathomatic install completed.
# 	@echo

# # The following installs shell scripts matho and rmath,
# # allowing convenient entry of standard math functions.
# # Requires at least "make bininstall" first.
# matho-rmath-install:
# 	$(INSTALL) -d $(DESTDIR)$(mathdatadir)
# 	$(INSTALL) -d $(DESTDIR)$(mathdatadir)/m4
# 	echo '#!/bin/sh' >$(M4SCRIPTPATH)
# 	echo '# Shell script to run Mathomatic with the GNU m4 preprocessor.' >>$(M4SCRIPTPATH)
# 	echo '# This allows entry of many standard math functions.' >>$(M4SCRIPTPATH)
# 	echo '#' >>$(M4SCRIPTPATH)
# 	echo '# Usage: matho [ input_files ]' >>$(M4SCRIPTPATH)
# 	echo >>$(M4SCRIPTPATH)
# 	echo 'if ! $(M4) --version >/dev/null' >>$(M4SCRIPTPATH)
# 	echo 'then' >>$(M4SCRIPTPATH)
# 	echo '  echo The $(M4) package is not installed.  GNU m4 is required to run m4 Mathomatic.' >>$(M4SCRIPTPATH)
# 	echo '  exit 1' >>$(M4SCRIPTPATH)
# 	echo 'fi' >>$(M4SCRIPTPATH)
# 	echo >>$(M4SCRIPTPATH)
# 	echo '$(M4) -eP -- $(mathdatadir)/m4/functions.m4 "$$@" - | mathomatic -ru -s-1' >>$(M4SCRIPTPATH)
# 	chmod 0755 $(M4SCRIPTPATH)
# 	$(INSTALL_PROGRAM) m4/rmath $(DESTDIR)$(bindir)
# 	$(INSTALL_DATA) rmath.1 $(DESTDIR)$(mandir)/man1
# 	cd $(DESTDIR)$(mandir)/man1 && ln -sf rmath.1 matho.1
# 	$(INSTALL_DATA) m4/functions.m4 m4/degrees.m4 m4/gradians.m4 $(DESTDIR)$(mathdatadir)/m4

# # Install m4 Mathomatic with trig functions that use degree units, instead of radians.
# matho-rmath-install-degrees: matho-rmath-install
# 	cat m4/degrees.m4 >>$(DESTDIR)$(mathdatadir)/m4/functions.m4
# 	@echo Degree mode installed.

# # Install complete m4 Mathomatic with trig functions that use degree units, instead of radians.
# m4install-degrees: m4install
# 	cat m4/degrees.m4 >>$(DESTDIR)$(mathdatadir)/m4/functions.m4
# 	@echo Degree mode installed.

# # Install the Mathomatic binaries and documentation.  Does not install m4 Mathomatic.
# install: bininstall docinstall
# 	@echo
# 	@echo Mathomatic is installed.
# 	@echo

# # Strip the binaries of their symbol tables.  Makes smaller executables, but debugging becomes impossible.
# strip: $(AOUT)
# 	strip $(AOUT)

# # Binaries only install.
# bininstall:
# 	$(INSTALL) -d $(DESTDIR)$(bindir)
# 	$(INSTALL) -d $(DESTDIR)$(datadir)/applications
# 	$(INSTALL) -d $(DESTDIR)$(datadir)/pixmaps
# 	$(INSTALL) -d $(DESTDIR)$(mandir)/man1
# 	$(INSTALL_PROGRAM) $(AOUT) $(DESTDIR)$(bindir)
# 	$(INSTALL_DATA) icons/mathomatic.desktop $(DESTDIR)$(datadir)/applications
# 	$(INSTALL_DATA) icons/mathomatic.png icons/mathomatic.xpm $(DESTDIR)$(datadir)/pixmaps
# 	$(INSTALL_DATA) mathomatic.1 $(DESTDIR)$(mandir)/man1

# # Documentation only install.
# docinstall:
# 	@echo Installing docs...
# 	$(INSTALL) -d $(DESTDIR)$(mathdocdir)
# 	$(INSTALL) -d $(DESTDIR)$(mathdocdir)/html
# 	$(INSTALL) -d $(DESTDIR)$(mathdocdir)/tests
# 	$(INSTALL) -d $(DESTDIR)$(mathdocdir)/examples
# 	$(INSTALL_DATA) $(TEXT_DOCS) $(DESTDIR)$(mathdocdir)
# 	$(INSTALL_DATA) doc/* $(DESTDIR)$(mathdocdir)/html
# 	-$(INSTALL_DATA) *.pdf $(DESTDIR)$(mathdocdir)
# 	$(INSTALL_DATA) tests/* $(DESTDIR)$(mathdocdir)/tests
# 	$(INSTALL_DATA) examples/* $(DESTDIR)$(mathdocdir)/examples

# # UNINSTALL MATHOMATIC

# # Entirely remove Mathomatic from your local computer system.
# uninstall:
# 	cd $(DESTDIR)$(mandir)/man1 && rm -f $(MAN1) matho.1
# 	cd $(DESTDIR)$(bindir) && rm -f $(AOUT) rmath matho
# 	rm -rf $(DESTDIR)$(mathdocdir)
# 	rm -rf $(DESTDIR)$(mathdatadir)
# 	rm -f $(DESTDIR)$(datadir)/applications/mathomatic.desktop
# 	rm -f $(DESTDIR)$(datadir)/pixmaps/mathomatic.*
# 	@echo
# 	@echo Mathomatic uninstall completed.
# 	@echo
# 	-$(MAKE) -C primes prefix=$(prefix) uninstall
# 	@echo
# 	-$(MAKE) -C lib prefix=$(prefix) uninstall

# # CLEAN THIS DIRECTORY

# # Tidy this directory and sub-directories after building, testing, and installing Mathomatic.
# # Useful to run before a build make, to be sure we are building something complete and new.
# clean:
# 	rm -f *.o *.pyc *.pyo
# 	rm -f */*.o */*.pyc */*.pyo
# 	rm -f tests/test.out primes/test.out primes/bigtest.out

# # distclean cleans everything to the defaults, before distributing the source code
# # from this directory, if it has not been corrupted or carelessly modified.
# distclean: clean
# 	rm -f *.a */*.a
# 	rm -f $(AOUT)
# 	rm -f mathomatic_secure
# 	rm -f *.exe
# 	rm -f *.pdf
# 	$(MAKE) -C primes distclean
# 	$(MAKE) -C lib distclean

# # maintainer-clean prepares to rebuild absolutely everything.  Not recommended.
# maintainer-clean flush: distclean
# 	rm -f $(MANHTML)
# 	./update # shell script to update proto.h using the cproto utility.

# # make a clean distribution out of this directory in ~/am.zip
# zip: distclean
# 	./zipsrc # shell script

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
